inventory:
  armor:
  - null
  - null
  - null
  - null
  contents:
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_LILY
    amount: 64
