inventory:
  armor:
  - null
  - null
  - null
  - null
  contents:
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:mundane
  - null
  - null
  - null
  - null
  - null
config:
  showContents: true
